config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'flights#index'
  resources :flights, only: [:index, :show]
  get '/flights/search', to: 'flights#search', as: 'search_flights'
end

app/models/airline.rb
class Airline < ApplicationRecord
    has_many :flights
end

app/models/airport.rb
class Airport < ApplicationRecord
    has_many :departing_flights, class_name: "Flight", foreign_key: "origin_airport_id"
    has_many :arriving_flights, class_name: "Flight", foreign_key: "destination_airport_id"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  belongs_to :booking_status
  belongs_to :passenger
  belongs_to :flight_class
end

app/models/booking_status.rb
class BookingStatus < ApplicationRecord
    has_many :bookings
end

app/models/flight.rb
class Flight < ApplicationRecord
    belongs_to :airline 
    belongs_to :origin_airport, class_name: 'Airport'
    belongs_to :destination_airport, class_name: 'Airport'
    has_many :bookings
    has_many :passengers
end

app/models/flight_class.rb
class FlightClass < ApplicationRecord
    has_many :bookings
end

app/models/passenger.rb
class Passenger < ApplicationRecord
    has_many :bookings
    has_many :flights, through: :bookingd
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
   
    def index
        @flights = Flight.all
    end

    def new
        @flight = Flight.new
    end

    def search
        origin = params[:from]
        destination = params[:to]
        departure_date = params[:depart]
        return_date = params[:return]
        
        @flights = Flight.where(origin_city: origin, destination_city: destination, departure_date: departure_date, return_date: return_date)
        
        # Pass @flights to the view for rendering
      end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/f_lights_helper.rb
module FLightsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/flights/_flight_search_form.html.erb
<div class="items-center">
  <%= form_for :flight_search, url: search_flights_path, method: :get, html: { class: 'max-w-md mx-auto' } do |f| %>
    <div class="mb-4">
      <%= f.label :from, class: 'mb-2' %>
      <%= f.text_field :from, class: '' %>
    </div>
    <div class="mb-4">
      <%= f.label :to, class: 'mb-6 mt-6' %>
      <%= f.text_field :to, class: 'form-input' %>
    </div>
    <div class="mb-4">
      <%= f.label :depart, class: '' %>
      <%= f.date_select :depart, class: '' %>
    </div>
    <div class="mb-4">
      <%= f.label :return, class: '' %>
      <%= f.date_select :return, class: '' %>
    </div>
    <div class="mb-4">
      <%= f.label :passengers, class: '' %>
      <%= f.number_field :passengers, class: '' %>
    </div>
    <div class="text-center">
      <%= f.button :submit, class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded' %>
    </div>
  <% end %>
</div>

app/views/flights/index.html.erb
<div class="text-center">
    <h1 class="font-bold text-2xl mb-8">Welcome to Canoë</h1>
</div>

<div class="items-center">
    <%= render partial: 'flight_search_form' %>
</div>

app/views/flights/search.html.erb
<div class="mx-auto flex justify-center">
    <div class="text-center">
        <h1>Flights search results </h1>
        <h2>From <%= @departure_airport.name %> to <%= @arrival_airport.name %></h2>
        <% @flights.each do |flight| %>
        <%# Complete search results here %>
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flightproject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/home.html.erb
<div class="mx-auto justify-center">
    <div class="text-center">
        <h1>Welcome to Canoë</h1>
    </div>
    <%= render partial: 'shared/flight_search_form' %>
</div>